Repository BayAreaMetro/tm2py, pull requests merged in 2022-04, with the labels that each got.

#16 WIP: Architecture/Organization
  README.md
  bin/get_test_data
  bin/get_test_data.bat
  bin/tm2py
  bin/update_docs
  configs/version/model_config_v0_0_0.toml
  docs/api.md
  docs/architecture.md
  environment.yml
  examples/README.md
  examples/model_config.toml
  examples/scenario_config.toml
  mkdocs.yml
  requirements.txt
  setup.py
  tests/test_config.py
  tests/test_tests.py
  tests/test_tools.py
  tests/test_union_city.py
  tm2py/__init__.py
  tm2py/_api.py
  tm2py/_version.py
  tm2py/components/__init__.py
  tm2py/components/component.py
  tm2py/components/demand/__init__.py
  tm2py/components/demand/air_passenger.py
  tm2py/components/demand/commercial.py
  tm2py/components/demand/demand.py
  tm2py/components/demand/household.py
  tm2py/components/demand/internal_external.py
  tm2py/components/demand/visitor.py
  tm2py/components/network/__init__.py
  tm2py/components/network/highway/__init__.py
  tm2py/components/network/highway/highway_assign.py
  tm2py/components/network/highway/highway_maz.py
  tm2py/components/network/highway/highway_network.py
  tm2py/components/network/transit/__init__.py
  tm2py/components/network/transit/transit_assign.py
  tm2py/components/network/transit/transit_skim.py
  tm2py/config.py
  tm2py/controller.py
  tm2py/emme/__init__.py
  tm2py/emme/manager.py
  tm2py/emme/matrix.py
  tm2py/emme/network.py
  tm2py/examples.py
  tm2py/logger.py
  tm2py/template.py
  tm2py/tools.py
Labels: refactor

#48 FIX: bug in building documentation
  docs/api.md
  mkdocs.yml
  tests/test_docs.py
  tests/test_tools.py
Labels: bug

#49 Fix Union City test package compatibility across branch Config versions
  examples/model_config.toml
  examples/scenario_config.toml
  tests/test_config.py
  tests/test_tools.py
  tests/test_union_city.py
Labels: bug

#50 Fix docs build fail - Again
  docs/requirements.txt
Labels: bug

#63 Create CODEOWNERS
  CODEOWNERS
Labels: chore
