Repository BayAreaMetro/tm2py, pull requests merged in 2022-05, with the labels that each got.

#67 Separate Union City Model Runs as Testing Fixture
  tests/test_docs.py
  tests/test_union_city.py
Labels: docs

#73 Doc Versioning
  .github/workflows/clean.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/contributing/development.md
  docs/index.md
  environment.yml
  mkdocs.yml
  requirements.txt
  tests/README.md
Labels: docs, chore

#55 Entrypoint
  CONTRIBUTING.md
  README.md
  bin/tm2py
  bin/tm2py.bat
  docs/README.md
  docs/api.md
  docs/contributing/development.md
  docs/contributing/documentation.md
  docs/examples/README.md
  docs/examples/configuration.md
  docs/examples/restart_model.ipynb
  docs/examples/run_model.ipynb
  docs/index.md
  docs/starting.md
  mkdocs.yml
  requirements.txt
  tests/test_docs.py
  tests/test_union_city.py
  tm2py/components/network/highway/highway_assign.py
  tm2py/controller.py
Labels: feature

#65 Add mermaid diagrams for what happens when we run the model.
  docs/README.md
Labels: docs

#78 Fix breaking Auto-documentation for Pydantic Dataclasses
  docs/api.md
  tm2py/config.py
Labels: bug

#81 Example testing fixtures
  docs/api.md
  tests/conftest.py
  tests/test_config.py
  tests/test_tools.py
  tests/test_union_city.py
  tm2py/tools.py
Labels: chore

#53 Basic Input validation
  tests/test_config.py
  tests/test_union_city.py
  tm2py/components/component.py
  tm2py/components/network/highway/highway_network.py
  tm2py/controller.py
Labels: feature

#52 Develop logging
  docs/contributing/development.md
  examples/model_config.toml
  tests/test_config.py
  tests/test_logging.py
  tests/test_union_city.py
  tm2py/components/component.py
  tm2py/components/network/highway/highway_assign.py
  tm2py/components/network/highway/highway_maz.py
  tm2py/components/network/highway/highway_network.py
  tm2py/config.py
  tm2py/controller.py
  tm2py/logger.py
Labels: feature

#58 Fix os path compatibility
  examples/model_config.toml
  examples/scenario_config.toml
  tm2py/components/component.py
  tm2py/components/demand/demand.py
  tm2py/config.py
  tm2py/controller.py
  tm2py/tools.py
Labels: bug
